version: '3'
services:
  supply-chain:
    image: supply-chain:latest
    build:
      context: .
    command: "npm run start:concord"
    ports:
      - 4200:4200
    volumes:
      - ../resources/supply-chain/contracts:/app/contracts
      - ../resources/supply-chain/src/app/core/blockchain/:/app/src/app/core/blockchain/
      - ../resources/supply-chain/migrations:/app/migrations
      - ../resources/supply-chain/build:/app/build
      - ../resources/supply-chain/truffle-config.js:/app/truffle-config.js
      - ../resources/supply-chain/package.json:/app/package.json
      - ../resources/supply-chain/verify:/app/verify
    environment:
      # Example
      # - BC_URL=https://localhost.vmware.com/api/blockchains/<blockchain-id>
      - BC_URL=https://supply-chain.vmware.com/api/blockchains/1
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      priv-eth-net1:


  concord-truffle:
    image: concord-truffle:latest
    tty: true
    volumes:
      - ../resources/truffle:/truffle
    networks:
      priv-eth-net1:

  concord1:
    image: concord-node:latest
    ports:
      - 5458:5458
    expose:
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    volumes:
      - ../resources/devdata/rocksdbdata1:/concord/rocksdbdata
      - ../resources/devdata/log1:/concord/log
      - ../resources/config-concord1:/concord/config-local
      - ../resources/config-public:/concord/config-public:ro
      - ../resources/tls_certs:/concord/tls_certs:ro
    networks:
      priv-eth-net1:

  ethrpc1:
    image: concord-ethrpc:latest
    ports:
      - 8545:8545
    volumes:
      - ../resources/config-ethrpc1:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord1:5458
    networks:
      priv-eth-net1:

  concord2:
    image: concord-node:latest
    ports:
      - 5459:5458
    expose:
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    volumes:
      - ../resources/devdata/rocksdbdata2:/concord/rocksdbdata
      - ../resources/devdata/log2:/concord/log
      - ../resources/config-concord2:/concord/config-local
      - ../resources/config-public:/concord/config-public:ro
      - ../resources/tls_certs:/concord/tls_certs:ro
    networks:
      priv-eth-net1:

  ethrpc2:
    image: concord-ethrpc:latest
    ports:
      - 8546:8545
    volumes:
      - ../resources/config-ethrpc2:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord2:5458
    networks:
      priv-eth-net1:

  concord3:
    image: concord-node:latest
    ports:
      - 5460:5458
    expose:
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    volumes:
      - ../resources/devdata/rocksdbdata3:/concord/rocksdbdata
      - ../resources/devdata/log3:/concord/log
      - ../resources/config-concord3:/concord/config-local
      - ../resources/config-public:/concord/config-public:ro
      - ../resources/tls_certs:/concord/tls_certs:ro
    networks:
      priv-eth-net1:

  ethrpc3:
    image: concord-ethrpc:latest
    ports:
      - 8547:8545
    volumes:
      - ../resources/config-ethrpc3:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord3:5458
    networks:
      priv-eth-net1:

  concord4:
    image: concord-node:latest
    ports:
      - 5461:5458
    expose:
      - 3501/tcp
      - 3502/tcp
      - 3503/tcp
      - 3504/tcp
      - 3505/tcp
    volumes:
      - ../resources/devdata/rocksdbdata4:/concord/rocksdbdata
      - ../resources/devdata/log4:/concord/log
      - ../resources/config-concord4:/concord/config-local
      - ../resources/config-public:/concord/config-public:ro
      - ../resources/tls_certs:/concord/tls_certs:ro
    networks:
      priv-eth-net1:

  ethrpc4:
    image: concord-ethrpc:latest
    ports:
      - 8548:8545
    volumes:
      - ../resources/config-ethrpc4:/config:ro
    command:
      - java
      - -jar
      - concord-ethrpc.jar
      - --ConcordAuthorities=concord4:5458
    networks:
      priv-eth-net1:

networks:
  priv-eth-net1:
    driver: bridge
#    driver: overlay
    ipam:
      config:
      - subnet: 172.16.254.0/28

